# pixi kommandon
pixi init projekt_name
pixi add python jupyterlab pandas
pixi run jupyter lab

In [17]:
name = "Hanad"
print(name)

Hanad

In [18]:
fullname = name + " Ahmed"
print (fullname)

Hanad Ahmed

In [1]:
import pandas as pd

In [2]:


url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

column_names = [
    'sepal_length',
    'sepal_width',
    'petal_length',
    'petal_width',
    'species'
]

iris_df = pd.read_csv(url, names=column_names)

print(iris_df.head())

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [3]:
iris_df.describe(include='all')

        sepal_length  sepal_width  petal_length  petal_width      species
count     150.000000   150.000000    150.000000   150.000000          150
unique           NaN          NaN           NaN          NaN            3
top              NaN          NaN           NaN          NaN  Iris-setosa
freq             NaN          NaN           NaN          NaN           50
mean        5.843333     3.054000      3.758667     1.198667          NaN
std         0.828066     0.433594      1.764420     0.763161          NaN
min         4.300000     2.000000      1.000000     0.100000          NaN
25%         5.100000     2.800000      1.600000     0.300000          NaN
50%         5.800000     3.000000      4.350000     1.300000          NaN
75%         6.400000     3.300000      5.100000     1.800000          NaN
max         7.900000     4.400000      6.900000     2.500000          NaN

In [4]:
mean_speal_lenght = iris_df['sepal_length'].mean()
print(mean_speal_lenght)

5.843333333333334

In [5]:
mean_per_species= iris_df.groupby('species').mean()
mean_per_species

                 sepal_length  sepal_width  petal_length  petal_width
species
Iris-setosa             5.006        3.418         1.464        0.244
Iris-versicolor         5.936        2.770         4.260        1.326
Iris-virginica          6.588        2.974         5.552        2.026

In [6]:
filtered_df = iris_df[iris_df['petal_length'] > 3.0]
print(filtered_df.head())

    sepal_length  sepal_width  petal_length  petal_width          species
50           7.0          3.2           4.7          1.4  Iris-versicolor
51           6.4          3.2           4.5          1.5  Iris-versicolor
52           6.9          3.1           4.9          1.5  Iris-versicolor
53           5.5          2.3           4.0          1.3  Iris-versicolor
54           6.5          2.8           4.6          1.5  Iris-versicolor